print('-=-'*5, '\033[1;32;40mDESAFIO 002\033[m', '-=-'*5)
frase = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(frase))
print('Só tem espaços?', frase.isspace())
print('É um número?', frase.isnumeric())
print('É alfabético?', frase.isalpha())
print('É alfanúmerico?', frase.isalnum())
print('Está em maiúscula?', frase.isupper())
print('Está em minúscula?', frase.islower())
print('Está capitalizado?', frase.istitle())
